# Generated by Django 3.1.4 on 2020-12-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Done')], default=0, max_length=9),
        ),
    ]
