# Generated by Django 3.1.4 on 2021-01-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201230_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator_collections', to='api.customuser'),
            preserve_default=False,
        ),
    ]
