# Generated by Django 3.1.4 on 2021-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_collectioninvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioninvite',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE')], default='PENDING', max_length=9),
        ),
    ]
