# Generated by Django 3.1.4 on 2021-01-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_collectioninvite_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioninvite',
            name='status',
        ),
    ]
