# Generated by Django 3.1.4 on 2021-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_collectioninvite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioninvite',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE')], default='PENDING', max_length=9),
        ),
    ]
